#Execute the queries, get the counts and use them to do fisher exact test for each of the variables
fish_data=matrix(c(6,167,76,1966),nrow=2,dimnames=list(Group=c('C','O'),cardiac_arrest=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(10,163,116,1926),nrow=2,dimnames=list(Group=c('C','O'),defibrillation_events=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(62,111,592,1450),nrow=2,dimnames=list(Group=c('C','O'),myocardial_infarction=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(67,106,653,1389),nrow=2,dimnames=list(Group=c('C','O'),stroke=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(2,171,21,2021),nrow=2,dimnames=list(Group=c('C','O'),sudden_cardiac_death=c('1','0')))
fisher.test(fish_data)

fish_data=matrix(c(30,143,271,1771),nrow=2,dimnames=list(Group=c('C','O'),amputation=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(106,67,819,1223),nrow=2,dimnames=list(Group=c('C','O'),angioplasty=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(106,67,956,1086),nrow=2,dimnames=list(Group=c('C','O'),bypass=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(160,13,1371,671),nrow=2,dimnames=list(Group=c('C','O'),revascularization=c('1','0')))
fisher.test(fish_data)

fish_data=matrix(c(93,80,1034,1008),nrow=2,dimnames=list(Group=c('C','O'),arrhythmias=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(50,123,531,1511),nrow=2,dimnames=list(Group=c('C','O'),atrial_fibrillation=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(53,120,478,1564),nrow=2,dimnames=list(Group=c('C','O'),conduction_disease_bradyarrythmia=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(71,102,707,1335),nrow=2,dimnames=list(Group=c('C','O'),dizziness=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(42,131,290,1752),nrow=2,dimnames=list(Group=c('C','O'),palpitations=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(71,102,778,1264),nrow=2,dimnames=list(Group=c('C','O'),tachycardia=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(3,170,37,2005),nrow=2,dimnames=list(Group=c('C','O'),ventricular_fibrillation=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(16,157,125,1917),nrow=2,dimnames=list(Group=c('C','O'),ventricular_tachycardia=c('1','0')))
fisher.test(fish_data)


fish_data=matrix(c(85,88,984,1058),nrow=2,dimnames=list(Group=c('C','O'),congestive_heart_failure=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(58,115,584,1458),nrow=2,dimnames=list(Group=c('C','O'),diabetes=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(138,35,1333,709),nrow=2,dimnames=list(Group=c('C','O'),dyslipidemias=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(155,18,1672,370),nrow=2,dimnames=list(Group=c('C','O'),hypertension=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(38,135,433,1609),nrow=2,dimnames=list(Group=c('C','O'),renal_failure=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(136,37,1411,631),nrow=2,dimnames=list(Group=c('C','O'),ace_inhibitors=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(102,71,1066,976),nrow=2,dimnames=list(Group=c('C','O'),antiarrhythmics=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(156,17,1571,471),nrow=2,dimnames=list(Group=c('C','O'),aspirin=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(134,39,1230,812),nrow=2,dimnames=list(Group=c('C','O'),beta_blocking_agents=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(96,77,693,1349),nrow=2,dimnames=list(Group=c('C','O'),clopidogrel=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(67,106,699,1343),nrow=2,dimnames=list(Group=c('C','O'),diabetes_drugs=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(142,31,1412,630),nrow=2,dimnames=list(Group=c('C','O'),statins=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(58,115,631,1411),nrow=2,dimnames=list(Group=c('C','O'),warfarin=c('1','0')))
fisher.test(fish_data)

fish_data=matrix(c(107,66,1165,877),nrow=2,dimnames=list(Group=c('C','O'),gender=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(98,75,998,1044),nrow=2,dimnames=list(Group=c('C','O'),mace=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(166,7,1529,513),nrow=2,dimnames=list(Group=c('C','O'),mace=c('1','0')))
fisher.test(fish_data)
fish_data=matrix(c(116,57,1267,775),nrow=2,dimnames=list(Group=c('C','O'),as=c('1','0')))
fisher.test(fish_data)

#problem 3.1. model data is obtained by executing the query provided in the homework notes and creating a csv file
model_data=read.csv("model_data.csv",header=TRUE)
model = glm(cil_group ~ dyslipidemias+hypertension+ace_inhibitors+aspirin+beta_blocking_agents+clopidogrel+statins, family = binomial,data = model_data)
model_data$ps=model$fitted
library("Matching")
m = Match(Tr=model_data$cil_group, X=model_data$ps,replace=F, M=5)
newIndices = m$MatchLoopC[,2]
control_data=model_data[newIndices,]
comp_data=rbind(control_data,model_data[model_data$cil_group==1,])

#Do fisher test for each of the variables after matching
fisher.test(table(comp_data$cardiac_arrest,comp_data$cil_group))
fisher.test(table(comp_data$defibrillation,comp_data$cil_group))
fisher.test(table(comp_data$myocardial_infarction,comp_data$cil_group))
fisher.test(table(comp_data$stroke,comp_data$cil_group))
fisher.test(table(comp_data$sudden_cardiac_death,comp_data$cil_group))
fisher.test(table(comp_data$amputation,comp_data$cil_group))
fisher.test(table(comp_data$angioplasty,comp_data$cil_group))
fisher.test(table(comp_data$bypass,comp_data$cil_group))
fisher.test(table(comp_data$revascularization,comp_data$cil_group))
fisher.test(table(comp_data$arrhythmias,comp_data$cil_group))
fisher.test(table(comp_data$atrial_fibrillation,comp_data$cil_group))
fisher.test(table(comp_data$cdb,comp_data$cil_group))
fisher.test(table(comp_data$dizziness,comp_data$cil_group))
fisher.test(table(comp_data$palpitations,comp_data$cil_group))
fisher.test(table(comp_data$tachycardia,comp_data$cil_group))
fisher.test(table(comp_data$ventricular_fibrillation,comp_data$cil_group))
fisher.test(table(comp_data$ventricular_tachycardia,comp_data$cil_group))
fisher.test(table(comp_data$congestive_heart_failure,comp_data$cil_group))
fisher.test(table(comp_data$diabetes,comp_data$cil_group))
fisher.test(table(comp_data$dyslipidemias,comp_data$cil_group))
fisher.test(table(comp_data$hypertension,comp_data$cil_group))
fisher.test(table(comp_data$renal_failure,comp_data$cil_group))
fisher.test(table(comp_data$ace_inhibitors,comp_data$cil_group))
fisher.test(table(comp_data$antiarrhythmics,comp_data$cil_group))
fisher.test(table(comp_data$aspirin,comp_data$cil_group))
fisher.test(table(comp_data$beta_blocking_agents,comp_data$cil_group))
fisher.test(table(comp_data$clopidogrel,comp_data$cil_group))
fisher.test(table(comp_data$diabetes_drugs,comp_data$cil_group))
fisher.test(table(comp_data$statins,comp_data$cil_group))
fisher.test(table(comp_data$warfarin,comp_data$cil_group))

#plot has been created on local machine with only the propensity score and frequency data from the model. No raw data has been extracted.
cil=hist(model_data[model_data$cil_group==1,]$ps,plot=FALSE)
oth=hist(model_data[model_data$cil_group==0,]$ps,plot=FALSE)
plot(cil$mids,cil$counts,ylim=c(0,600),xlab='ps',ylab='freq')
lines(cil$mids,cil$counts)
points(oth$mids,oth$counts)
lines(oth$mids,oth$counts)
